package net.deechael.genshin.api.entity;

public enum CommonEnemy implements EntityType {

    // Elemental Lifeforms
    SLIME_ANEMO,
    SLIME_CRYO,
    SLIME_DENDRO,
    SLIME_ELECTRO,
    SLIME_GEO,
    SLIME_HYDRO,
    SLIME_PYRO,
    LARGE_SLIME_ANEMO,
    LARGE_SLIME_CRYO,
    LARGE_SLIME_DENDRO,
    LARGE_SLIME_ELECTRO,
    LARGE_SLIME_MUTANT_ELECTRO,
    LARGE_SLIME_GEO,
    LARGE_SLIME_HYDRO,
    LARGE_SLIME_PYRO,
    SPECTER_ANEMO,
    SPECTER_CRYO,
    SPECTER_DENDRO,
    SPECTER_ELECTRO,
    SPECTER_GEO,
    SPECTER_HYDRO,
    SPECTER_PYRO,
    WHOPPERFLOWER_CRYO,
    WHOPPERFLOWER_PYRO,
    WHOPPERFLOWER_ELECTRO,
    FLOATING_FUNGI_ANEMO,
    FLOATING_FUNGI_DENDRO,
    FLOATING_FUNGI_HYDRO,
    STRETCHY_FUNGI_ANEMO,
    STRETCHY_FUNGI_ELECTRO,
    STRETCHY_FUNGI_GEO,
    STRETCHY_FUNGI_PYRO,
    WHIRLING_FUNGI_CRYO,
    WHIRLING_FUNGI_ELECTRO,
    WHIRLING_FUNGI_PYRO,
    GROUNDED_SHROOM_GEO,
    GROUNDED_SHROOM_HYDRO,
    WINGED_SHROOM_CRYO,
    WINGED_SHROOM_DENDRO,
    CICIN_CRYO,
    CICIN_ELECTRO,
    CICIN_HYDRO,

    // Hilichurls
    HILICHURL,
    HILICHURL_FIGHTER,
    HILICHURL_BERSERKER,
    HILICHURL_GUARD_WOODEN,
    HILICHURL_GUARD_ROCK,
    HILICHURL_GUARD_ICE,
    HILICHURL_GRENADIER_PYRO,
    HILICHURL_GRENADIER_CRYO,
    HILICHURL_GRENADIER_ELECTRO,
    HILICHURL_SHOOTER,
    HILICHURL_SHOOTER_ELECTRO,
    HILICHURL_SHOOTER_CRYO,
    HILICHURL_SHOOTER_PYRO,
    SAMACHURL_ANEMO,
    SAMACHURL_CRYO,
    SAMACHURL_DENDRO,
    SAMACHURL_ELECTRO,
    SAMACHURL_GEO,
    SAMACHURL_HYDRO,
    UNUSAL_HILICHURL,

    // Fatui
    FATUI_SKIRMISHER_VANGUARD_ANEMO,
    FATUI_SKIRMISHER_VANGUARD_ELECTRO,
    FATUI_SKIRMISHER_BRACER_GEO,
    FATUI_SKIRMISHER_BRACER_PYRO,
    FATUI_SKIRMISHER_LEGIONNAIRE_CRYO,
    FATUI_SKIRMISHER_LEGIONNAIRE_HYDRO,

    // Treasure Hoarder
    TREASURE_HOARDER_CRUSHER,
    TREASURE_HOARDER_GRAVEDIGGER,
    TREASURE_HOARDER_MARKSMAN,
    TREASURE_HOARDER_SCOUT,
    TREASURE_HOARDER_HANDYMAN,
    TREASURE_HOARDER_PUGILIST,
    TREASURE_HOARDER_SEAMAN,
    TREASURE_HOARDER_POTIONEER_ELECTRO,
    TREASURE_HOARDER_POTIONEER_CRYO,
    TREASURE_HOARDER_POTIONEER_HYDRO,
    TREASURE_HOARDER_POTIONEER_PYRO,

    // Nobushi & Kairagi
    NOBUSHI_HITSUKEBAN,
    NOBUSHI_JINTOUBAN,
    NOBUSHI_KIKOUBAN,
    KAIRAGI_THUNDER,
    KAIRAGI_FIERY_MIGHT,

    // The Eremites
    EREMITE_VANGUARD, // I like her!!!! - DeeChael
    EREMITE_CROSSBOW,
    EREMITE_DAYTHUNDER,
    EREMITE_CLEARWATER,
    EREMITE_GALEHUNTER, // Beautiful Lady, kick me plz - DeeChael
    EREMITE_LINEBREAKER,
    EREMITE_HALBERDIER,
    EREMITE_STONE,
    EREMITE_SUNROST,
    EREMITE_DANCER;

    // Genshin Impact 3.1 end

}
