package net.deechael.genshin.api.entity;

public enum EliteEnemy implements EntityType {

    // Hilichurls
    SHIELDWALL_MITACHURL_WOODEN,
    SHIELDWALL_MITACHURL_ROCK,
    SHIELDWALL_MITACHURL_ICE,
    AXE_MITACHURL_BLAZING,
    AXE_MITACHURL_CRACKLING,
    LAWACHURL_STONEHIDE,
    LAWACHURL_FROSTARM,
    LAWACHURL_THUNDERHELM,

    // The Abyss
    ABYSS_MAGE_HYDRO,
    ABYSS_MAGE_CRYO,
    ABYSS_MAGE_PYRO,
    ABYSS_MAGE_ELECTRO,
    ABYSS_HERALD_TORRENTS,
    ABYSS_LECTOR_FLAME,
    ABYSS_LECTOR_LIGHTNING,
    RIFTHOUND_WHELP_ROCKFOND,
    RIFTHOUND_WHELP_THUNDER,
    RIFTHOUND_ROCKFOND,
    RIFTHOUND_THUNDER,
    THE_BLACK_SERPENT_DEFENDER,
    THE_BLACK_SERPENT_LINEBREAKER,
    THE_BLACK_SERPENT_FLAGBEARER,
    THE_BLACK_SERPENT_WINDCUTTER,

    // Automations
    HUMANOID_RUIN_MACHINE_GUARD,
    HUMANOID_RUIN_MACHINE_HUNTER,
    HUMANOID_RUIN_MACHINE_GRADER,
    RUIN_SENTINEL_CRUISER,
    RUIN_SENTINEL_DESTROYER,
    RUIN_SENTINEL_DEFENDER,
    RUIN_SENTINEL_SCOUT,
    RUIN_DRAKE_EARTHGUARD,
    RUIN_DRAKE_SKYWATCH,
    PRIMAL_CONSTRUCT_PROSPECTOR,
    PRIMAL_CONSTRUCT_REPULSOR,
    PRIMAL_CONSTRUCT_RESHAPER,

    // Fatui
    FATUI_CICIN_MAGE_ELECTRO,
    FATUI_CICIN_MAGE_CRYO,
    FATUI_AGENT_PYRO,
    MIRROR_MAIDEN,

    // Mystical Beasts
    GEOVISHAP_HATCHLING,
    GEOVISHAP,
    BATHYSMAL_VISHAP_HATCHLING_BOLTEATER,
    BATHYSMAL_VISHAP_HATCHLING_PRIMORDIAL,
    BATHYSMAL_VISHAP_HATCHLING_RIMEBITER,
    BATHYSMAL_VISHAP_PRIMORDIAL,

    // Elemental Lifeforms
    EYE_OF_THE_STORM,

    // Others
    THE_GREAT_SNOWBOAR_KING,

    // Genshin Impact 3.1

}
