package net.deechael.genshin.api.entity;

public enum NormalBoss implements EntityType {

    HYPOSTASIS_ANEMO,
    HYPOSTASIS_ELECTRO,
    HYPOSTASIS_GEO,
    HYPOSTASIS_CRYO,
    HYPOSTASIS_PYRO,
    HYPOSTASIS_HYDRO,
    HYPOSTASIS_DENDRO, // 3.2
    REGISVINE_CRYO,
    REGISVINE_PYRO,
    REGISVINE_ELECTRO,
    RHODEIA_OF_LOCH,
    PRIMO_GEOVISHAP,
    MAGUU_KENKI,
    PERPETUAL_MECHANICAL_ARRAY,
    THUNDER_MANIFESTATION,
    GOLDEN_WOLFLORD,
    CORAL_DEFENDER,
    RUIN_SERPENT,
    JADEPLUME_TERRORSHROOM,
    AEONBLIGHT_DRAKE,
    ALGORITHM_OF_SEMI_INTRANSIENT_MATRIX_OF_OVERSEER_NETWORK,

    // Genshin Impact 3.1

}
